import DistributedCluster
import DistributedKit
import Foundation

// MARK: - Pretty Printing

let startTime = ContinuousClock.now

func log(_ icon: String, _ msg: String) {
    let elapsed = ContinuousClock.now - startTime
    let ms = Int(elapsed.components.seconds * 1000) + Int(elapsed.components.attoseconds / 1_000_000_000_000_000)
    print(String(format: "  %@  %4dms  %@", icon, ms, msg))
}

// MARK: - Demo

print()
print("  ╔══════════════════════════════════════════════╗")
print("  ║     DistributedKit  ·  Supervision Demo      ║")
print("  ╚══════════════════════════════════════════════╝")
print()

// --- Phase 1: Boot the cluster ---

log("⚡", "Booting ClusterSystem...")
let system = await ClusterSystem("Demo") { settings in
    settings.bindPort = 12001
    settings.logging.logLevel = .critical
}
log("✓", "ClusterSystem ready on :12001")

// --- Phase 2: Build supervision tree using @Service-generated childSpec() ---

print()
log("🌳", "Building supervision tree...")

// Worker.childSpec() is generated by the @Service macro.
// For custom restart strategies or names, use ChildSpec directly.
let tree = SupervisorTree("DemoApp") {
    Supervisor("workers", strategy: .oneForOne) {
        Worker.childSpec()  // @Service macro: name="worker", restart=.permanent
        ChildSpec<Worker>(
            name: "charlie",
            restart: .transient,
            factory: { sys in Worker(actorSystem: sys) }
        )
    }
}

log("✓", "Tree: DemoApp")
log(" ", "  └─ Supervisor 'workers' (oneForOne)")
log(" ", "       ├─ worker   [permanent]  ← Worker.childSpec()")
log(" ", "       └─ charlie  [transient]  ← manual ChildSpec")

// --- Phase 3: Start workers ---

print()
log("🚀", "Starting workers...")

let alice = Worker(actorSystem: system)
try await alice.setLabel("Alice")

let bob = Worker(actorSystem: system)
try await bob.setLabel("Bob")

let charlie = Worker(actorSystem: system)
try await charlie.setLabel("Charlie")

// Register in the registry
let registry = Registry(system: system)
await registry.register(alice, key: ServiceKey(id: "alice"))
await registry.register(bob, key: ServiceKey(id: "bob"))
await registry.register(charlie, key: ServiceKey(id: "charlie"))

log("✓", "Alice   registered → ServiceKey(id: \"alice\")")
log("✓", "Bob     registered → ServiceKey(id: \"bob\")")
log("✓", "Charlie registered → ServiceKey(id: \"charlie\")")

// --- Phase 4: Send work via processCast ---

print()
log("📨", "Dispatching work via handleCast (processCast helper)...")

for i in 1...3 {
    let a = try await alice.doWork("task-\(i)")
    log("→", "Alice.doWork()   → jobs_processed=\(a)")
}

for i in 1...2 {
    let b = try await bob.doWork("task-\(i)")
    log("→", "Bob.doWork()     → jobs_processed=\(b)")
}

let c = try await charlie.doWork("task-1")
log("→", "Charlie.doWork() → jobs_processed=\(c)")

// --- Phase 5: Query state via processCall ---

print()
log("📞", "Querying state via handleCall (processCall helper)...")

log("←", try await alice.status())
log("←", try await bob.status())
log("←", try await charlie.status())

// --- Phase 6: Registry lookup ---

print()
log("🔍", "Looking up actors via Registry...")

if let foundAlice: Worker = await registry.lookup(ServiceKey(id: "alice")) {
    log("✓", "registry.lookup(\"alice\") → \(try await foundAlice.status())")
}

if let foundBob: Worker = await registry.lookup(ServiceKey(id: "bob")) {
    log("✓", "registry.lookup(\"bob\")   → \(try await foundBob.status())")
}

// --- Phase 7: Simulate crash + restart ---

print()
log("💥", "Simulating crash: Charlie.simulateCrash()")
try await charlie.simulateCrash()
log("☠️", "Charlie state: \(try await charlie.status())")

log("🔄", "Supervisor detects crash → applying .oneForOne strategy")
log(" ", "  Charlie.restart = .transient → restart on error ✓")

// Simulate supervisor restarting Charlie with fresh state
let charlie2 = Worker(actorSystem: system)
try await charlie2.setLabel("Charlie-v2")
await registry.register(charlie2, key: ServiceKey(id: "charlie"))
log("✓", "Charlie restarted as Charlie-v2 (fresh state)")
log("←", try await charlie2.status())

// --- Phase 8: Verify Bob is unaffected (oneForOne) ---

print()
log("🛡️", "Verifying .oneForOne: Bob should be unaffected...")
log("✓", "Bob is fine: \(try await bob.status())")

// --- Phase 9: Show @Service macro info ---

print()
print("  ┌─────────────────────────────────────────────────────┐")
print("  │  @Service macro generates:                          │")
print("  │    • actorSystem property (if not present)          │")
print("  │    • static childSpec() for supervision trees       │")
print("  │    • DistributedKitService conformance              │")
print("  │      → serviceName: \"\(Worker.serviceName)\"" + String(repeating: " ", count: 27 - Worker.serviceName.count) + "│")
print("  │      → restartStrategy: .\(Worker.restartStrategy)" + String(repeating: " ", count: 22 - "\(Worker.restartStrategy)".count) + "│")
print("  └─────────────────────────────────────────────────────┘")
print()

try system.shutdown()
log("⏏", "ClusterSystem shut down. Done.")
print()
