import DistributedCluster
import DistributedKit

print("=== DistributedKit SampleWorker ===\n")

// 1. Boot a single-node cluster
let system = await ClusterSystem("SampleWorker") { settings in
    settings.bindPort = 11001
}

// 2. Create a counter worker (uses @Service macro)
let counter = CounterWorker(actorSystem: system)

// 3. Register with the typed Registry
let registry = Registry(system: system)
let key = ServiceKey<CounterWorker>(id: "counter")
await registry.register(counter, key: key)

print("[1] Created and registered CounterWorker (@Service macro)")

// 4. Use call/cast through distributed func API
try await counter.increment()
try await counter.increment()
try await counter.increment()
print("[2] Incremented 3 times")

try await counter.add(7)
print("[3] Added 7")

let count = try await counter.getCount()
print("[4] Current count: \(count)")  // 10

try await counter.decrement()
let finalCount = try await counter.getCount()
print("[5] After decrement: \(finalCount)")  // 9

// 5. Lookup via Registry
if let found = await registry.lookup(key) {
    let lookedUpCount = try await found.getCount()
    print("[6] Registry lookup count: \(lookedUpCount)")
} else {
    print("[6] ERROR: Registry lookup returned nil")
}

// 6. Singleton resolution (requires @Service for DistributedKitService conformance)
let resolved = try await Singleton<CounterWorker>.resolve(on: system)
let resolvedCount = try await resolved.getCount()
print("[7] Singleton.resolve count: \(resolvedCount)")

// 7. Supervision tree using macro-generated childSpec()
let tree = SupervisorTree("SampleApp") {
    Supervisor(strategy: .oneForOne) {
        CounterWorker.childSpec()  // Generated by @Service macro
    }
}

print("[8] SupervisorTree '\(tree.name)' with \(tree.children.count) child supervisor")

// 8. Show what @Service generates
print("\n--- @Service macro provides ---")
print("  serviceName:      \(CounterWorker.serviceName)")
print("  restartStrategy:  \(CounterWorker.restartStrategy)")

print("\n=== All checks passed ===")

try system.shutdown()
